services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile

    restart: unless-stopped

    working_dir: /var/www

    volumes:
      - ./:/var/www

    networks:
      - sinodtech


  nginx:
    image: ${DOCKER_NGINX_IMAGE}

    restart: unless-stopped

    ports:
      - "${DOCKER_APP_PORT}:80"

    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d

    depends_on:
      - app

    networks:
      - sinodtech


  mysql:
    image: ${DOCKER_MYSQL_IMAGE}

    restart: unless-stopped

    ports:
      - "${DOCKER_DB_PORT}:3306"

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - sinodtech


  phpmyadmin:
    image: ${DOCKER_PHPMYADMIN_IMAGE}

    restart: unless-stopped

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "${DOCKER_PHPMYADMIN_PORT}:80"

    depends_on:
      - mysql

    networks:
      - sinodtech

  redis:
    image: ${DOCKER_REDIS_IMAGE}

    restart: unless-stopped

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    networks:
      - sinodtech


networks:
  sinodtech:
    driver: bridge


volumes:
  mysql_data:
  redis_data:
